- src/db_rows.rs
> Enabling refactoring of the metadata resolver

- .github/workflows/cd.yaml
- .github/workflows/release.yaml
- .gitignore
- scripts/redeploy.sh
> Creating release workflow

- migrations/2022-10-19-105202_filter_listing_views/down.sql
- migrations/2022-10-19-105202_filter_listing_views/up.sql
> 🗃️ Exclude non-owned/burned tokens from listings

- src/db_rows.rs
This PR
- [ x] does a DB schema change
> Optional metadata id, listings

- hasura/metadata/databases/minterop/tables/public_nft_listings.yaml
- hasura/metadata/databases/minterop/tables/public_nft_offers.yaml
- migrations/2022-10-22-142201_add_invalidated_at/down.sql
- migrations/2022-10-22-142201_add_invalidated_at/up.sql
- scripts/unpin-db.sh
- src/db_rows.rs
- src/schema.rs
https://github.com/Mintbase/minterop-producer/pull/11
> Add invalidated columns for listings and offers 

- migrations/2022-10-26-090840_unfilter_listing_views/down.sql
- migrations/2022-10-26-090840_unfilter_listing_views/up.sql
> Undoing listing views filtering

- hasura/metadata/databases/minterop/tables/mb_views_auctions_with_offer.yaml
- migrations/2022-10-26-143936_views-invalidation-updates/down.sql
- migrations/2022-10-26-143936_views-invalidation-updates/up.sql
> Using invalidation columns in views

- hasura/metadata/databases/minterop/tables/public_nft_earnings.yaml
- migrations/2022-10-26-143936_views-invalidation-updates/up.sql
- migrations/2022-10-27-082801_mb-earnings-tracking/down.sql
- migrations/2022-10-27-082801_mb-earnings-tracking/up.sql
- src/db_rows.rs
- src/schema.rs
> Tracking MB earnings

- hasura/metadata/databases/minterop/tables/public_nft_listings.yaml
- hasura/metadata/databases/minterop/tables/public_nft_offers.yaml
> 🗃️ Add metadata_id perms to nft_listings

- hasura/metadata/databases/minterop/tables/public_nft_listings.yaml
- src/schema.rs
> Listings -> Token relationship

- migrations/2022-11-02-140120_filter-unburned-meta-prices/down.sql
- migrations/2022-11-02-140120_filter-unburned-meta-prices/up.sql
Addresses: https://app.asana.com/0/1202958620861943/1203229789028379/f
This PR
> Entering empty price to unburned metadata after invalidation

- migrations/2022-11-02-152113_fix-tokens-with-listing/down.sql
- migrations/2022-11-02-152113_fix-tokens-with-listing/up.sql
> Removing token/listing multiplication

- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens_with_media.yaml
- hasura/metadata/databases/minterop/tables/tables.yaml
- migrations/2022-11-07-195418_media-type-view/down.sql
- migrations/2022-11-07-195418_media-type-view/up.sql
This PR
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203307283770823
> 🗃️ Add media (animation) info via reference blob

- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens_with_media.yaml
> 🗃️ Fix table target for hasura permissions

- hasura/metadata/databases/minterop/tables/mb_views_active_listings.yaml
- hasura/metadata/databases/minterop/tables/mb_views_active_listings_rollup.yaml
- hasura/metadata/databases/minterop/tables/mb_views_auctions_with_offer.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_activities.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata_unburned.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_owned_tokens.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens_with_listing.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens_with_media.yaml
- hasura/metadata/databases/minterop/tables/public_nft_metadata.yaml
- migrations/2022-11-09-105840_token_flagging/down.sql
- migrations/2022-11-09-105840_token_flagging/up.sql
- src/schema.rs
> Enabling flagging single tokens

- migrations/2022-11-15-220956_improve_unburned_metadata/down.sql
- migrations/2022-11-15-220956_improve_unburned_metadata/up.sql
This PR
- no updates needed to hasura, same fields with different approach
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203367697533162
> 🗃️ Use lateral joins on metadata unburned

- migrations/2022-11-17-130240_fix_unburned_view/down.sql
- migrations/2022-11-17-130240_fix_unburned_view/up.sql
> 🚑 Filter out metadata rows without tokens

- hasura/metadata/databases/minterop/tables/mb_views_nft_activities.yaml
> Adding mb_views.nft_activities -> nft_contract relationship

- src/rpc_payloads.rs
> Adding sale payload

- src/db_rows.rs
> Make all tables queryable

- hasura/metadata/databases/minterop/tables/mb_views_nft_owned_tokens.yaml
- migrations/2022-12-15-141928_owned_tokens_with_listing/down.sql
- migrations/2022-12-15-141928_owned_tokens_with_listing/up.sql
> Adding listing info to owned tokens view

- hasura/metadata/databases/minterop/tables/mb_views_nft_activities.yaml
- migrations/2022-12-27-104743_activities-metadata-id/down.sql
- migrations/2022-12-27-104743_activities-metadata-id/up.sql
> Adding metadata ID to activities view

- hasura/metadata/databases/minterop/tables/mb_views_nft_activities_rollup.yaml
- migrations/2023-01-02-123603_activities-rollup/down.sql
- migrations/2023-01-02-123603_activities-rollup/up.sql
> Activities rollup

- hasura/metadata/databases/minterop/tables/analytics_tmp_referrer_earnings.yaml
- hasura/metadata/databases/minterop/tables/tables.yaml
- migrations/2023-01-17-114206_earnings-analytics-tmp/down.sql
- migrations/2023-01-17-114206_earnings-analytics-tmp/up.sql
- scripts/redeploy.sh
> Adding referral tracking and tmp analytics schema

- scripts/redeploy.sh
- src/schema.rs
> Hotfixing analytics view

- migrations/2023-01-20-122039_listings-distinct-by-meta/down.sql
- migrations/2023-01-20-122039_listings-distinct-by-meta/up.sql
> feat: :card_file_box: Use distinct meta for listings

- hasura/metadata/databases/minterop/tables/analytics_tmp_referrer_earnings_monthly.yaml
- hasura/metadata/databases/minterop/tables/analytics_tmp_referrer_earnings_yearly.yaml
- hasura/metadata/databases/minterop/tables/tables.yaml
- migrations/2023-01-20-122717_analytics-earnings-yearly/down.sql
- migrations/2023-01-20-122717_analytics-earnings-yearly/up.sql
> Yearly and monthly resolutions

- migrations/2023-02-15-120157_attributes-search-index/down.sql
- migrations/2023-02-15-120157_attributes-search-index/up.sql
> Add index to speed up searching by attributes

- src/db_rows.rs
- src/rpc_payloads.rs
> Prepare for NEP423

- hasura/metadata/databases/minterop/tables/mb_views_active_listings.yaml
- hasura/metadata/databases/minterop/tables/mb_views_active_listings_by_contract.yaml
- hasura/metadata/databases/minterop/tables/mb_views_active_listings_rollup.yaml
- hasura/metadata/databases/minterop/tables/mb_views_auctions_with_offer.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata_unburned.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_owned_tokens.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens_with_listing.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens_with_media.yaml
- hasura/metadata/databases/minterop/tables/public_nft_contracts.yaml
- hasura/metadata/databases/minterop/tables/public_nft_listings.yaml
- migrations/2023-03-03-122905_contract-categories/down.sql
- migrations/2023-03-03-122905_contract-categories/up.sql
- src/db_rows.rs
- src/schema.rs
> Add category column to contracts

- migrations/2023-03-03-180418_fix-affiliate-earnings/up.sql
> Hotfixing affiliate-earnings

- hasura/metadata/databases/minterop/tables/analytics_tmp_affiliate_earnings.yaml
- hasura/metadata/databases/minterop/tables/analytics_tmp_affiliate_earnings_monthly.yaml
- hasura/metadata/databases/minterop/tables/analytics_tmp_affiliate_earnings_yearly.yaml
- hasura/metadata/databases/minterop/tables/mb_views_active_listings_by_contract.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_activities_rollup.yaml
- hasura/metadata/databases/minterop/tables/public_nft_activities.yaml
- migrations/2023-04-27-141730_currency-fixes/down.sql
- migrations/2023-04-27-141730_currency-fixes/up.sql
- src/db_rows.rs
- src/schema.rs
> Currency fixes

- hasura/metadata/databases/minterop/tables/mb_views_nft_activities.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_activities_rollup.yaml
> Hotfix hasura perms

- hasura/metadata/databases/minterop/tables/mb_views_nft_activities_rollup.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata_unburned.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_tokens_with_listing.yaml
- migrations/2023-05-02-094810_more-currency-fixes/down.sql
- migrations/2023-05-02-094810_more-currency-fixes/up.sql
> Currencify all the places

- migrations/2023-05-02-094810_more-currency-fixes/down.sql
- migrations/2023-05-02-094810_more-currency-fixes/up.sql
> Hotfixing stuffs

- hasura/metadata/query_collections.yaml
> Fixing store endpoint

- hasura/metadata/databases/minterop/tables/mb_views_nft_notifications.yaml
- migrations/2023-05-03-102113_notifications-view/down.sql
- migrations/2023-05-03-102113_notifications-view/up.sql
> Implementing notifications view

- hasura/metadata/databases/minterop/tables/tables.yaml
> Including notification permissions

- hasura/metadata/databases/minterop/tables/mb_views_nft_notifications.yaml
> Adding metadata relationship to notifications

- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata_unburned.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_notifications.yaml
- migrations/2023-05-23-150921_unburned-metadata-listed-by/down.sql
- migrations/2023-05-23-150921_unburned-metadata-listed-by/up.sql
> Add `listed_by` to `mb_views.nft_metadata_unburned`

- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata.yaml
- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata_unburned.yaml
- migrations/2023-06-01-144354_metadata-views-reference/down.sql
- migrations/2023-06-01-144354_metadata-views-reference/up.sql
> Add reference to metadata views

- hasura/metadata/databases/databases.yaml
> Add query launchpad smart contract IDs

- migrations/2023-07-18-092402_owned-metadata-view/down.sql
- migrations/2023-07-18-092402_owned-metadata-view/up.sql
- migrations/2023-07-19-151644_reorder-active-listings-rollup-by-timestamp/down.sql
- migrations/2023-07-19-151644_reorder-active-listings-rollup-by-timestamp/up.sql
> Reorder active_listings_rollup by timestamp

- migrations/2023-07-18-092402_owned-metadata-view/down.sql
- migrations/2023-07-18-092402_owned-metadata-view/up.sql
> Remove artifacts

- hasura/metadata/databases/minterop/tables/mb_views_nft_metadata_unburned.yaml
- migrations/2023-08-09-091613_unburned-metadata-listing-created-at/down.sql
- migrations/2023-08-09-091613_unburned-metadata-listing-created-at/up.sql
> Add `listing_created_at` to `mb_views.nft_metadata_unburned`

- hasura/metadata/databases/minterop/tables/public_nft_metadata.yaml
- migrations/2023-11-15-114503_lazy-minting-support/down.sql
- migrations/2023-11-15-114503_lazy-minting-support/up.sql
- src/db_rows.rs
- src/rpc_payloads.rs
- src/schema.rs
> Add metadata payload

- .github/workflows/ci.yaml
- migrations/2024-02-19-154405_account-by-key-query-index/down.sql
- migrations/2024-02-19-154405_account-by-key-query-index/up.sql
- src/rpc_payloads.rs
> Create index to speed up querying account ID by public key

- .gitignore
- hasura/metadata/databases/minterop/tables/public_nft_metadata.yaml
- migrations/2024-05-14-105251_unique-minters/down.sql
- migrations/2024-05-14-105251_unique-minters/up.sql
- src/db_rows.rs
- src/rpc_payloads.rs
- src/schema.rs
> Unique minters
